name: Release

on:
  workflow_dispatch:
    inputs:
      releaseType:
        description: The type of release. Should be one of "major", "minor", "patch"
        required: true
        default: 'patch'
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-20.04
    name: Validate
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      - name: Run Biome
        run: biome ci .

      - name: Install dependencies
        run: pnpm install  

      - name: Generate output files
        env:
          SERVER: https://api.paradym.id
        run: pnpm generate

      - name: Build packages
        run: pnpm build
  release:
    runs-on: ubuntu-20.04
    name: Release
    needs: [validate]
    # Only run on workflow dispatch to main branch
    if: github.ref == 'refs/heads/main' && github.repository == 'animo/paradym-sdk-ts' && github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: git config
        run: |
          git config user.name "@github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Set Verbose Logging
        run: npm config set loglevel verbose --global

      - name: Set NPM config
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN }}" >> .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "always-auth=true" >> .npmrc
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the library
        run: pnpm build

      # On manual workflow dispatch release stable version
      - name: Release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm release ${{ github.event.inputs.releaseType }}